# @package _global_

defaults:
  - base_nontorch

eval:
  kwargs:
    retrain: True  # By default, models are retrained (causually, i.e. when predicting sample 100 it is trained on samples 1-99) on dataset when evaluated (val/test).
